language: minimal
os: osx
script:
  - curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  - bash Miniconda3-latest-MacOSX-x86_64.sh -b -p miniconda
  - for PYVER in 2.7 3.4 3.5 3.6 3.7; do miniconda/bin/conda create -y -n $PYVER matplotlib numpy six astropy scipy pytest-runner six; done
