env:
  # - PYVERSIONS="2.7 3.4 3.5 3.6 3.7" VERSION=1.12.4 V=1
  - PYVERSIONS="2.7" VERSION=1.12.4 V=1
language: minimal
os: osx
script:
  - curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  - bash Miniconda3-latest-MacOSX-x86_64.sh -b -p miniconda
  - source miniconda/bin/activate
  - conda install -y gcc
  - pip install delocate
  - for PYVERSION in $PYVERSIONS; do conda create -y -n $PYVERSION python==$PYVERSION.\* gcc matplotlib numpy six astropy scipy pytest-runner six; done
  - for PYVERSION in $PYVERSIONS; do (source miniconda/bin/activate; pip wheel --no-deps healpy==$VERSION); done
  - for WHEEL in *.whl; do delocate-wheel $WHEEL -w wheelhouse; done
